{
 "title": "Thanos",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Yearly Arm Time",
   "type": "bargauge",
   "description": "time spent in arm mode in the past year",
   "gridPos": { "h": 19, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(armTime[1y:1m]))by(appName)/60)",
     "legendFormat": "{{appName﻿}}"
    }
   ]
  },
  {
   "title": "Monthly Arm Time",
   "type": "bargauge",
   "description": "time spent in arm mode in the last month",
   "gridPos": { "h": 19, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(armTime[30d:1m]))by(appName)/60)",
     "legendFormat": "{{appName}}"
    }
   ]
  },
  {
   "title": "Raw Arm Time",
   "type": "graph",
   "description": "time spent in arm mode",
   "gridPos": { "h": 19, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "armTime / 60" }
   ]
  }
 ]
}